name: kusai-ce
version: "3.15"
summary: Kusai Analytics OLAP Tool (Community Edition)
description: |
  OLAP Browser for relational datasources. Open source. More info at
  Meteorite.bi

grade: devel
confinement: devmode

apps:
  run:
    command: $SNAP/start-saiku.sh
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH

parts:
  compile-saiku:
    source: ./
    plugin: x_maven
    maven-targets:
      - kusai-server
    maven-options: [-DskipTests]
